version: "3"
services:

    db:
        image: postgres
        networks:
            - network1
    
    web:
        image: django-web
        build: ./todolist
        
        networks:
            - network1
        restart: always
        
        depends_on:
            - db

        ports:
            - "8080:8080"
            
networks:
    network1:
